version: "3.9"

services:

  library-manager-php:
    container_name: library-manager-php
    hostname: php
    build:
      context: .
      target: php-build
      dockerfile: Dockerfile
    env_file:
      - .env.local
    entrypoint: symfony local:server:start --no-tls --port=80
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

    depends_on:
      - library-manager-mysql
    ports:
      - "8080:80"

  library-manager-mysql:
    container_name: library-manager-mysql
    image: mysql:8.0.28
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TEST_DATABASE: app_test
      MYSQL_TEST_USER: app_test
      MYSQL_TEST_PASSWORD: app_test
