<?php

namespace App\Tests\E2E\Books;

use GuzzleHttp\Client;

class DeleteBookTest extends \PHPUnit\Framework\TestCase
{

    //TODO: 1) Spostare $ip tra le variabili di ambiente

    private $ip;
    private $client;

    protected function setUp(): void
    {
        $this->ip = '192.168.1.109';
        $this->client = new Client([
            'base_uri' => "http://{$this->ip}:8080",
            'http_errors' => false,
        ]);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

    }


    public function testItDeletesExistingBook()
    {
        $res = $this->client->delete('/api/books/1');
        self::assertEquals(204, $res->getStatusCode());
    }

    public function testItHandlesDeleteNonExistentBook()
    {
        $res = $this->client->delete('/api/books/9999');
        self::assertEquals(404, $res->getStatusCode());
        self::assertEquals('Error: Book not found', json_decode($res->getBody()->getContents())->error);
    }
}