<?php

namespace App\Tests\E2E\Book;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class GetAllBooksTest extends WebTestCase
{
    private $client;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();

    }

    public function testItGetsAllBooks()
    {
        $this->client->request("GET", '/api/books?offset=0&limit=5');
        $res = $this->client->getResponse();
        $this->assertResponseIsSuccessful();
        $quantity = count(json_decode($res->getContent())->data);


        self::assertEquals(200, $res->getStatusCode());
        self::assertEquals(5, $quantity);
    }
}