name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: create env
        working-directory: ./backend
        run: cat>.env.local

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build NGINX Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend/docker/ngnix
          dockerfile: ./backend/docker/ngnix/Dockerfile
          load: true
          tags: library-manager-nginx:latest

      - name: Build PHP Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend/docker/php
          dockerfile: ./backend/docker/php/Dockerfile
          load: true
          tags: library-manager-php:latest

      - name: up
        working-directory: ./backend
        run: make up

      - name: Run PHP-CS-Check
        working-directory: ./backend
        run: |
          make php-cs-check
      - name: Run PHPStan
        working-directory: ./backend
        run: |
          make php-stan
      - name: Run tests
        working-directory: ./backend
        run: |
          make test-all