name: Continuous Integration
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Compose
        uses: docker/compose@1.29.2
        with:
          compose-file: docker-compose.yml
      - name: Build and run containers
        run: |
          docker-compose build ${PHP_CONTAINER} --no-cache
          docker-compose up -d
          sleep 10
          docker exec ${PHP_CONTAINER} sh -c "composer install -o"
      - name: Run tests
        run: |
          docker exec -e XDEBUG_MODE=off ${PHP_CONTAINER} sh -c "php bin/phpunit --testdox"
          docker-compose exec -e XDEBUG_MODE=coverage ${PHP_CONTAINER} vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-html coverage
          docker exec -e XDEBUG_MODE=off ${PHP_CONTAINER} sh -c "php vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --config .php-cs-fixer.dist.php -v"
          docker exec -e XDEBUG_MODE=off ${PHP_CONTAINER} sh -c "php vendor/bin/php-cs-fixer fix --using-cache=no --config .php-cs-fixer.dist.php -v"
          docker exec ${PHP_CONTAINER} sh -c "php bin/console doctrine:migrations:migrate"
          docker exec ${PHP_CONTAINER} sh -c "php bin/console import-books ${filter}"
      - name: Run PhpStan
        run: docker exec -e XDEBUG_MODE=off ${PHP_CONTAINER} sh -c "vendor/bin/phpstan analyse -c phpstan.neon"
